export {default as Navbar} from './Navbar/Navbar'
export {default as  Footer} from './Footer/Footer'
export {default as  Hero} from './Hero/Hero'
export {default as  Tourism} from './Tourism/Tourism'
export {default as  Oneclick} from './Oneclick/Oneclick'
export {default as  Destination} from './Destination/Destinaton'
export {default as  Travel} from './Travel/Travel'